### PR TITLE
Address Field Validation Modules

### PR DESCRIPTION
**Pull request by jigarius**
Basic Drupal Commerce installation along with Address Field Validation modules.

### CODE REVIEW

**Comment by dergachev** [comment]
Great stuff, we're very impressed!!! Here are our rough feedback notes, let me know when you'd like to go over them.

Reviewed Jigar's code with DV
- Give us a PR, please
- Write clear docs, fix README merge error
- Run drupalcs
- Simplify code / removed - where? Eg. to reduce lines of code.
- Please share updated time logs, include ALL time spent (not just "billable").
- CC Dave on all communications!
- catch only SoapFault exceptions, but what about others?
  - [https://github.com/jrm1987/fedex-address-validation/blob/master/docroot/sites/all/modules/custom/addressfield_validation_fedex/addressfield_validation_fedex.module#L203](https://github.com/jrm1987/fedex-address-validation/blob/master/docroot/sites/all/modules/custom/addressfield_validation_fedex/addressfield_validation_fedex.module#L203)
- DV says $response->HighestSeverity might not be set, then also could be an error case
  - [https://github.com/jrm1987/fedex-address-validation/blob/master/docroot/sites/all/modules/custom/addressfield_validation_fedex/addressfield_validation_fedex.module#L208](https://github.com/jrm1987/fedex-address-validation/blob/master/docroot/sites/all/modules/custom/addressfield_validation_fedex/addressfield_validation_fedex.module#L208)
- Why not watchdog in all errors?
- On line 66, has an unconditional read of property; need to check isset
- the function _addressfield_validation_fedex_validate is too big, split this into testable chunks
  - (Split into build_request, do_remote_call, handle_response; then can test easily)
- Now instead of a validation error, display error to reload the form, a workflow where we prompt to correct the address, and WARN that given address is invalid, with an option to override.
- We'd like to figure out if it's possible to AJAX validate the address, but it's out of scope for this challenge. (DONT DO THIS)
- Why did he do this for Billing address, he should ONLY do this for shipping! In fact, why didn't you enable the commerce_shipping module?
- We prefer a form_alter approach rather than element_validate. In any case we want to opt in (via admin UI or code) to which forms this acts on.
- testing On Acquia first time, an invalid address submission hung for 30s, then clicking on submit again triggered this:
  - [](https://dl.dropbox.com/u/29440342/screenshots/NKGPRBGA-2016.08.08-16-34-31.png)
  - [](https://dl.dropbox.com/u/29440342/screenshots/AWPADETC-2016.08.08-16-35-17.png)
- Results are a bit sluggish. Is it the fedex API being slow? Do you have a 5s timeout, with error fallback.

**Comment by jigarius** [comment]
ACTIVITY LOG
- Install Drupal 7 and all modules required for a basic Commerce site.
- Install features and strongarm module to create the features_commerce module.
- Study FedEx API to get a basic idea of how it would be working.
- Create test credentials, download and read necessary documentation.
- Search for and study any existing modules related to FedEx Address Validation.
- Study fedex_address_validation module and try to fix it's errors.
- fedex_address_validation module uses AVS WSDL Version 2 and the latest
  version is Version 4. Also, the module is minimally maintained and
  doesn't work out of the box. Hence it was decided to build a custom
  implementation of address validation using FedEx, borrowing parts of code
  from fedex_address_validation.
- Create addressfield_validation module to hook into addressfield submission
  and trigger a validation callback as per site configuration.
- Create addressfield_validation_fedex module to implement actual
  address validation.
- Create configuration page for addressfield_validation_fedex module and
  set up testing credentials.
- Create one callback function which would accept drupal addresses, validate
  it using FedEx AVS and return relevant results. This function would
  not have the responsibility to validate form elements, etc. Its only job
  would be to take addresses and validate them so that it can be used moreover
  as a stand-alone function when we need to validate addresses programatically.
- Implement form element validation callback as per addressfield_validation
  specifications. This function would take the FedEx AVS validation results
  and do something useful with it. For now, it only shows error messages and
  sets the form field as invalid as and when required.
- Create FedEx Address Validation Tests for Drupal simpletest module and configure
  various test cases to see if the FedEx AVS validation is working as expected.
- Deploy code to Acquia hosting and perform final set of tests.

TO-DO
- Display effective address (address as interpreted by FedEx AVS) to the user
  and ask them to confirm if it is correct or make changes to their input to
  remove any margin for errors.

[harvest_time_report_from20160801to20160807.xlsx](https://github.com/dergachev/fedex-address-validation/files/407804/harvest_time_report_from20160801to20160807.xlsx)

**Comment by vasi** [comment]
Ok, to summarize our review: Your work so far has been very good! Our main concerns now are error-handling, and allowing users to continue if validation is problematic.

Here are the subtasks you should work on next:
1. Fix major error-handling issues.
   - The module should produce no PHP error notices
   - The module should check all reasonable error conditions, eg: if HighestSeverity is unset
   - If the server is down, the user should be allowed to continue
   - All errors should be logged with watchdog
2. Only validate addresses on certain forms. On some forms (eg: checkout pane), the shipping address should be validated. On other forms (address book, backend) the shipping address should not be validated.
3. Allow users to override Fedex validation. If the validation flags an error, the user should be able to continue anyway if they want.

Other smaller issues that we identified are not a high priority. You can work on them if you want, but try not to spend more than half an hour on any such issue.

Remember to log all your time, even if it isn't billable.

**Comment by vasi** [comment]
Here's a sample notice we saw during our review:

notice

**Comment by jigarius** [comment]
ACTIVITIES
- Fixed the merge error which had been created. I need to study about merges.
  Will do it after I make this FedEx module stable.
- Added commerce_shipping and commerce_flat_rate modules to make the demo more realistic.
- Removed the address_validation module.
- Renamed and address_validation_fedex module to fedex_avs - it is now an API only module. All it   does is validation. No more overhead of providers, etc.
- Refactored fedex_avs's code to handle errors in a better way. I hope I got all errors this time - they are all logged into watchdog.
- Created a fedex_avs_addressfield module integrating fedex_avs with addressfield
- Added fedex_avs configuration elements to addressfield instance config forms
- Implemented addressfield widget validation as per widget settings
- Implemented bypass mechanism - user can now check a box to bypass
  FedEx AVS warnings and errors.
- Added a 5 second request timeout - if required, we can make it a back end
  configuration parameter later.
- Added provision for validating (or not validating) specific form-ids. For now
  the admin can enter a list of Form IDs manually and choose whether it is a
  white-list or a black-list. I spent 15-20 minutes trying to figure out how
  to create a list of forms available on the site (for generating checkboxes),
  but it seems there is no direct list. If needed, later, I can look up the
  menu_routes table where "page callback" = "drupal_get_form" and treat the
  first page argument as a Form ID (I wasn't sure if you needed so much in the 
  UI for now, so I put it on the to-do list for now).
- Installed PHP PEAR and PHP_CodeSniffer to be able to run a Drupal code review.
- Updated the repository readme file to include installation and testing insturctions.

TIMESHEET

[harvest_time_report_from20160801to20160831.xlsx](https://github.com/dergachev/fedex-address-validation/files/411581/harvest_time_report_from20160801to20160831.xlsx)

**Comment by dergachev** [comment]
Testing out the code here:
http://evowebfedexaddvalvuiwpzfutf.devcloud.acquia-sites.com/checkout/36

**Comment by vasi** [comment]
This looks really good! You did all three tasks we asked for, and didn't take too much extra time doing less important things—good job.

Some nitpicks/advice for the future:
- When using git, you should try not to remove a complete module and then add it again. It's better to use 'git mv' to rename things—that way we can track changes, and figure out what you did.
- It seems strange that you couldn't get validation functions to change the form. Alex is pretty sure we've done that successfully in the past. At least $form_state should be possible to change? We'll test this out together later :)
- The option you chose for timeout, with `ini_set()`, seems like it would work. But generally we try to avoid `ini_set()` if possible, because it affects global behaviour if somehow it doesn't get changed back. Did you consider using the 'connection_timeout' parameter to SOAPClient instead? Would that be good enough?
- I'm glad you got Code Sniffer figured out! But it looks like something is still missing, because you didn't catch some Drupal standard violations. Eg: Comments should end in punctuation. We'll help you get this working later.
- The error handling looks better! There are still a few small issues though:
  *\* If AddressResults is missing, you consider that ok. Is that really ok?
  *\* You treat AddressResults as potentially an array of results in `fedex_avs_validate_addresses()`, but then `fedex_avs_addressfield_element_validate()` treats it as a single result object. That's a bit strange.
  *\* What error do we get if the socket timeout is exceeded? I don't see any handling for that. Maybe it's just SOAPFault?
  *\* If we get a SOAPFault, it looks like you consider that not an error. Which is good if it's a "Can't contact server" error. Are there other SOAPFaults that we should consider real errors? If not, we should have a comment explaining that.

Thanks! I look forward to continuing this work in a few weeks.

**Comment by jigarius** [comment]
Thanks for the feedback. I will keep those suggestions in mind.
1. I have altered form values with form_validate() callbacks, however after what I saw that day, I believe widget validation functions are not allowed to modify form structure. It was taking too much time, so I took a short-cut for the time being. Will experiment this weekend.
2. For the connection time out, I did consider _connection_timeout_, what it does is only limits the time taken to connect to the remote server. If the actual execution on the remote server takes a long time, it would not restrict that delay. Hence, I chose to use an _ini_set()_. Will check it and if it looks good, I will switch to _connection_timeout_.
3. I could install CodeSniffer, however, I could not get set the installed_paths for drupalcs. Maybe its some Windows thing - I set the path exactly as suggested by the installation guide for _coder/drupal_, but _phpcs_ throws exceptions saying path could not be read. So I decided to use the coder module. Will try and configure the Drupal standard for _phpcs_ again this weekend.
4. If _AddressResults_ is not set, it should be an error. However, as far as I observed, if _HighestSeverity_ is set, FedEx AVS always returns _AddressResults_ so I left it as it was. Will add an else case in line 197 to handle missing _AddressResults_ just in case.
5. I do convert the _AddressResults_ to an array to run them through a foreach loop and set error messages. However, in line 193, I change them back to as they were.
6. I didn't think about other SoapFault types. Will have to check if we have any other error codes, etc. I left it at that assuming that if there was a corner case with an unexpected type of SoapFault, we would be able to study it when we see it in the dblog. But I will see if there can be other types of SoapFaults.

Regards,

**Comment by vasi** [comment]
Looks great.

**Comment by dergachev** [comment]
Looks great, merging.

**Pull request closed without merging**
